### PR TITLE
jump by word

### PR DESCRIPTION
**Pull request by ctf0**
is is possible to make it jump by word instead of char ?
Sort Text acts strangely on ST3.

add some options to the Text Conversion.

### CODE REVIEW

**Comment by chaosphere2112** [comment]
Hi! Thanks for the pull request. The code looked good, but I'm not sure what you mean by jump by word; can you give me an example? I'll look into the ST3 issues with sort text.

**Comment by ctf0** [comment]
EX, (the red fox went to the woods) now move the word "fox" to left/right 
,in current state it will be either <code>(redfox <b>or</b> foxwent)</code> ,but what am after is <code>(fox red <b>or</b> went fox)</code> ,does it make any sense ?

**Comment by chaosphere2112** [comment]
Ah! Yeah, I can do that. I'll whip something up.

**Comment by ctf0** [comment]
awesome ,btw can you also add an option to show the duplicated lines,words b4 removing them ?

**Comment by chaosphere2112** [comment]
Yeah, that sounds like a good feature. I'll try and take some time this weekend to build these.

**Comment by ctf0** [comment]
any news ?

**Comment by chaosphere2112** [comment]
Sorry, yeah; I got a little sidetracked. I think I've got the shift done in one direction, still need to sort it out in the other. Hopefully will have some time this week to polish this off and commit it.

**Comment by ctf0** [comment]
okey ,no rush.

**Pull request merged**
